# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Test

    runs-on: ubuntu-latest

    timeout-minutes: 5

    env:
      OS: ubuntu-latest
      NODE_VERSION: 14.17.4

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.17.4
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.4
          cache: npm

      - name: Install packages
        run: npm i

      - name: Lint
        run: npm run lint
